/**
 * Renders the overhead comparison from the files scripts/overhead/run.sh
 * writes: k6's summary (latency, throughput, failures) and the process
 * metrics sampled from Prometheus, for the instrumented and baseline runs.
 *
 *   npx tsx scripts/overhead/report.ts [results-dir]
 */
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { platform, release, arch, cpus, totalmem } from 'node:os';

interface K6Summary {
  metrics: Record<string, { values: Record<string, number> }>;
}

interface ProcessSample {
  label: string;
  otelSdkDisabled: boolean;
  cpuCoresAvg: number;
  rssMaxBytes: number;
  eventLoopLagP99MaxSeconds: number;
  rate: number;
  duration: string;
  node: string;
  date: string;
}

interface Run {
  label: string;
  k6: K6Summary;
  process: ProcessSample;
}

const dir = process.argv[2] ?? join('scripts', 'overhead', 'results');

function load(label: string): Run | undefined {
  const k6Path = join(dir, `${label}.k6.json`);
  const processPath = join(dir, `${label}.process.json`);
  if (!existsSync(k6Path) || !existsSync(processPath)) return undefined;
  return {
    label,
    k6: JSON.parse(readFileSync(k6Path, 'utf8')) as K6Summary,
    process: JSON.parse(readFileSync(processPath, 'utf8')) as ProcessSample,
  };
}

const instrumented = load('instrumented');
const baseline = load('baseline');
if (!instrumented || !baseline) {
  console.error(`No results in ${dir}. Run ./scripts/overhead/run.sh first.`);
  process.exit(1);
}

const ms = (run: Run, stat: string): number =>
  run.k6.metrics.http_req_duration?.values[stat] ?? NaN;
const rps = (run: Run): number => run.k6.metrics.http_reqs?.values.rate ?? NaN;
const failed = (run: Run): number => run.k6.metrics.http_req_failed?.values.rate ?? NaN;

function delta(a: number, b: number, unit = ''): string {
  if (!Number.isFinite(a) || !Number.isFinite(b) || b === 0) return 'n/a';
  const diff = a - b;
  const pct = (diff / b) * 100;
  return `${diff >= 0 ? '+' : ''}${diff.toFixed(2)}${unit} (${pct >= 0 ? '+' : ''}${pct.toFixed(1)}%)`;
}

const rows: [string, string, string, string][] = [
  [
    'Throughput (req/s)',
    rps(instrumented).toFixed(1),
    rps(baseline).toFixed(1),
    delta(rps(instrumented), rps(baseline)),
  ],
  [
    'Latency p50 (ms)',
    ms(instrumented, 'med').toFixed(2),
    ms(baseline, 'med').toFixed(2),
    delta(ms(instrumented, 'med'), ms(baseline, 'med'), ' ms'),
  ],
  [
    'Latency p95 (ms)',
    ms(instrumented, 'p(95)').toFixed(2),
    ms(baseline, 'p(95)').toFixed(2),
    delta(ms(instrumented, 'p(95)'), ms(baseline, 'p(95)'), ' ms'),
  ],
  [
    'Latency p99 (ms)',
    ms(instrumented, 'p(99)').toFixed(2),
    ms(baseline, 'p(99)').toFixed(2),
    delta(ms(instrumented, 'p(99)'), ms(baseline, 'p(99)'), ' ms'),
  ],
  [
    'Failed requests',
    `${(failed(instrumented) * 100).toFixed(2)}%`,
    `${(failed(baseline) * 100).toFixed(2)}%`,
    '',
  ],
  [
    'api CPU (cores, avg)',
    instrumented.process.cpuCoresAvg.toFixed(3),
    baseline.process.cpuCoresAvg.toFixed(3),
    delta(instrumented.process.cpuCoresAvg, baseline.process.cpuCoresAvg),
  ],
  [
    'api RSS (MB, max)',
    (instrumented.process.rssMaxBytes / 1e6).toFixed(1),
    (baseline.process.rssMaxBytes / 1e6).toFixed(1),
    delta(instrumented.process.rssMaxBytes / 1e6, baseline.process.rssMaxBytes / 1e6, ' MB'),
  ],
  [
    'Event loop lag p99 (ms, max)',
    (instrumented.process.eventLoopLagP99MaxSeconds * 1000).toFixed(2),
    (baseline.process.eventLoopLagP99MaxSeconds * 1000).toFixed(2),
    delta(
      instrumented.process.eventLoopLagP99MaxSeconds * 1000,
      baseline.process.eventLoopLagP99MaxSeconds * 1000,
      ' ms',
    ),
  ],
];

const machine = `${platform()} ${release()} ${arch()}, ${String(cpus().length)} cores, ${(totalmem() / 2 ** 30).toFixed(0)} GB, Node ${instrumented.process.node}`;
console.log(`| Metric | Instrumented | Baseline (OTEL_SDK_DISABLED=true) | Delta |`);
console.log(`| --- | ---: | ---: | ---: |`);
for (const [metric, a, b, d] of rows) console.log(`| ${metric} | ${a} | ${b} | ${d} |`);
console.log();
console.log(
  `_${String(instrumented.process.rate)} req/s for ${instrumented.process.duration}, ${machine}, ${instrumented.process.date}. Generated by \`scripts/overhead/run.sh\` + \`report.ts\`; see docs/overhead.md for the method and its limits._`,
);
